# Site
name: "Kenner Kliemann"
description: "Aprendendo e compartilhando"
meta_description: "Criando minha própria realidade"
logo: 'assets/images/logo.png'
lang: pt-br
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'UA-128177289-1'
disqus: 'kennerkliemann'
mailchimp-list: ''

twitter:
  username: kennerkliemann
  card: summary

# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234

social:
  name: Kenner Kliemann
  links:
    - https://twitter.com/KennerKliemann
    - https://www.facebook.com/kenner.kliemann
    - http://br.linkedin.com/in/kennerkliemann
    - https://github.com/gnomex

github_username: gnomex

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
  kenner:
    name: Kenner Kliemann
    display_name: Kenner
    gravatar:
    email: kenner.hp@gmail.com
    web: https://github.com/gnomex
    twitter: https://twitter.com/KennerKliemann
    description: "Construindo um mundo melhor"    

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge